server:
  port: 9091
spring:
  application:
    name: activemq-producer-demo
# springboot与activemq的整合
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
# 指定发送模式(点对点:false,发布订阅:true)
  jms:
    pub-sub-domain: true
    template:
      delivery-mode: persistent # 持久化，存储在KahaDB
#      delivery-mode: non_persistent # 非持久化，存储在内存中
#    pub-sub-domain: false
activemq:
  name: springboot_topic
#  name: springboot_queue

